ProjPiDev/src/Entity/Commentaire.php
<?php

namespace App\Entity;

use App\Repository\CommentaireRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommentaireRepository::class)
 */
class Commentaire
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Description;

    /**
     * @ORM\Column(type="integer")
     */
    private $NbrReac;

    /**
     * @ORM\ManyToOne(targetEntity=Annonce::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $annonce;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $TimeStamp;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getNbrReac(): ?int
    {
        return $this->NbrReac;
    }

    public function setNbrReac(int $NbrReac): self
    {
        $this->NbrReac = $NbrReac;

        return $this;
    }

    public function getAnnonce(): ?Annonce
    {
        return $this->annonce;
    }

    public function setAnnonce(?Annonce $annonce): self
    {
        $this->annonce = $annonce;

        return $this;
    }

    public function getTimeStamp(): ?string
    {
        return $this->TimeStamp;
    }

    public function setTimeStamp(string $TimeStamp): self
    {
        $this->TimeStamp = $TimeStamp;

        return $this;
    }
}

ProjPiDev/src/Controller/DemandeEmploiController.php
<?php

namespace App\Controller;

use App\Entity\Demande;
use App\Form\DemandeType;

use App\Repository\DemandeRepository;
use Doctrine\ORM\EntityManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Dompdf\Dompdf;
use Dompdf\Options;
use Symfony\Component\HttpFoundation\File\File;


class DemandeEmploiController extends AbstractController
{
    /**
     * @Route("/Ajout/demande/emploi", name="Ajout_demande_emploi" , methods={"GET","POST"})
     * @param Request $request
     * @return Response
     */
    public function Ajout(Request $request): Response
    {

        $demande = new demande();
        $form = $this->createForm(DemandeType::class, $demande);
        $form->handleRequest($request);



        if ($form->isSubmitted()  ) {
            $file = $demande->getcvCand();
            $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();
            $file->move(
                $this->getParameter('upload_directory'),
                $fileName
            );
            $demande->setcvCand($fileName);
            

            $demande->setIdCand($this->getUser());
            $demande = $form->getData();
            $em = $this->getDoctrine()->getManager();
            $em->persist($demande);
            $em->flush();
            return $this->redirectToRoute("list_demande_emploi");


    }
        return $this->render('demande_emploi/Ajout_demande_emploi.html.twig',array('formdemande'=>$form->createView()));




    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }



    /**
     * @Route("/list/demande/emploi", name="list_demande_emploi" , methods={"GET"})
     * @param PaginatorInterface $paginator
     * @param Request $request
     * @return Response
     */
    public function listeD(PaginatorInterface $paginator, Request $request): Response
    {
        $userId = $this->getUser()->getId();
        $id = array('idCand' => $userId);
        $demande=$this->getDoctrine()->getRepository(Demande::class);
        $count=$demande->countNbDemande();
        $demandes=$demande->findby($id);

        $demandes = $paginator->paginate(
        // Doctrine Query, not results
            $demandes,
            // Define the page parameter
            $request->query->getInt('page', 1),
            // Items per page
            4
        );
        return $this->render('demande_emploi/liste_demande_emploi.html.twig',['demandes'=>$demandes , 'c'=>$count ]);
    }

    /**
     * @Route("/list/demande/back", name="list_demande_back" , methods={"GET"})
     */
    public function listeDB(): Response
    {

        $demande=$this->getDoctrine()->getRepository(Demande::class);
        $demandes=$demande->findAll();
        return $this->render('demande_emploi/liste_demande_back.html.twig',['demandes'=>$demandes , ]);

    }


    /**
     * @Route("/Supp/demande/emploi/{id}", name="Supp_demande_emploi" , methods={"GET","POST"})
     * @param Request $request
     * @param Demande $demande
     * @return Response
     */
    public function listeSu(Request $request, Demande $demande): Response
    {
       
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($demande);
            $entityManager->flush();

        return $this->redirectToRoute("list_demande_emploi");
    }


    /**
     * @Route("/Modif/demande/emploi/{id}", name="Modif_demande_emploi" , methods={"GET","POST"})
     * @param Request $request
     * @param $id
     * @return Response
     */
    public function listeModif(Request $request, $id): Response
    {

        $demande=$this->getDoctrine()->getRepository(Demande::class)->find($id);
        $form=$this->createForm(DemandeType::class,$demande);
        $form->handleRequest($request);
        if($form->isSubmitted())
        {
            $file = $demande->getcvCand();
            $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();
            $file->move(
                $this->getParameter('upload_directory'),
                $fileName
            );
            $demande->setcvCand($fileName);
            $em=$this->getDoctrine()->getManager();
            $em->flush();
            return $this->redirectToRoute("list_demande_emploi");
        }

        return $this->render("demande_emploi/Modif_demande_emploi.html.twig",array('formdemandeMod'=>$form->createView()));
    }


    /**
     * @Route("/list/demande/emploi/detail/{id}", name="list_demande_emploi_detail" , methods={"GET"})
     * @param $id
     * @return Response
     */
    public function listeDet($id): Response
    {

        $demande=$this->getDoctrine()->getRepository(Demande::class);
        $demande=$demande->find($id);
        return $this->render('demande_emploi/aff_demande_detail.html.twig',['demande'=>$demande , ]);


    }


    /**
     * @param DemandeRepository $repository
     * @param Request $request
     * @return Response
     * @Route("/tri", name="tri")
     */
    public function tri(DemandeRepository $repository,Request $request)
    {
        $demande= $repository->OrderByStatut();
        return $this->render('demande_emploi/search.html.twig', [
            'demande' => $demande,
        ]);
    }


    /**
     * @Route("/listdem", name="listdem", methods={"GET"})
     * @param DemandeRepository $demandeRepository
     * @return Response
     */
    public function listdem(DemandeRepository $demandeRepository): Response
    {
        // Configure Dompdf according to your needs
        $pdfOptions = new Options();
        $pdfOptions->set('defaultFont', 'Arial');

        // Instantiate Dompdf with our options
        $dompdf = new Dompdf($pdfOptions);
        // Retrieve the HTML generated in our twig file
        $html = $this->renderView('demande_emploi/listdem.html.twig', [
            'demandes' => $demandeRepository->findAll(),
        ]);


        // Load HTML to Dompdf
        $dompdf->loadHtml($html);

        // (Optional) Setup the paper size and orientation 'portrait' or 'portrait'
        $dompdf->setPaper('A4', 'portrait');

        // Render the HTML as PDF
        $dompdf->render();

        // Output the generated PDF to Browser (inline view)
        $dompdf->stream("Liste demande.pdf", [
            "Attachment" => false
        ]);
    }


    /**
     * @Route("/searchDemande ", name="searchDemande")
     * @param Request $request
     * @param NormalizerInterface $Normalizer
     * @return Response
     * @throws \Symfony\Component\Serializer\Exception\ExceptionInterface
     */
    public function searchDemande(Request $request,NormalizerInterface $Normalizer)
    {
        $repository = $this->getDoctrine()->getRepository(Demande::class);
        $requestString=$request->get('searchValue');
        $demande = $repository->findDemandePardomaineTravail($requestString);
        $jsonContent = $Normalizer->normalize($demande, 'json',['groups'=>'demande']);
        $retour=json_encode($jsonContent);
        return new Response($retour);

    }


    /**
     * @Route("/filtreDemande/{statutCand} ", name="filtreDemande")
     * @param NormalizerInterface $Normalizer
     * @param $statutCand
     * @return Response
     * @throws \Symfony\Component\Serializer\Exception\ExceptionInterface
     */
    public function filtreDemande(NormalizerInterface $Normalizer, $statutCand)
    {
        $repository = $this->getDoctrine()->getRepository(Demande::class);
        $demande = $repository->findStatutCand($statutCand);
        $jsonContent = $Normalizer->normalize($demande, 'json',['groups'=>'demande']);
        $retour=json_encode($jsonContent);
        return new Response($retour);
    }


}

ProjPiDev/templates/demande_emploi/Modif_demande_emploi.html.twig
{% extends 'base.html.twig' %}

{% block title %}Demande d'emploi{% endblock %}

{% block body %}
    <div class="page-heading contact-heading header-text" style="background-image: url({{asset('assets/images/heading-4-1920x500.jpg') }});">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="text-content">
                        <h4>Demande</h4>
                        <h2>Modifier votre demande</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="send-message">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="section-heading">
                        <h2>Votre demande</h2>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="contact-form">
                        <form id="contact" {{ form_start(formdemandeMod, {'attr':{'novalidate':'novalidate'}}) }}
                        <div class="row">
                            <div class="col-lg-12 col-md-12 col-sm-12"> Titre
                                {{ form_errors(formdemandeMod.TitreDemande) }}
                                {{ form_widget(formdemandeMod.TitreDemande) }}

                            </div>
                            <div class="col-lg-12 col-md-12 col-sm-12"> Votre domaine
                                {{ form_errors(formdemandeMod.domaineTravail) }}
                                {{ form_widget(formdemandeMod.domaineTravail) }}

                            </div>
                            <div class="col-lg-12"> Votre Statut
                                {{ form_errors(formdemandeMod.statutCand) }}
                                {{ form_widget(formdemandeMod.statutCand) }}

                            </div>
                            <div class="col-lg-12"> Description
                                {{ form_errors(formdemandeMod.description) }}
                                {{ form_widget(formdemandeMod.description) }}

                            </div>
                            <div class="col-lg-12 col-md-12 col-sm-12"> CV
                                {{ form_errors(formdemandeMod.cvCand) }}
                                {{ form_widget(formdemandeMod.cvCand) }}
                            </div>
                            <div class="col-lg-12">
                                <button type="submit" id="form-submit" class="filled-button">{{ button_label|default('Enregistrer')}}</button>
                            </div>
                        </div>
                        </form {{ form_end(formdemandeMod) }}
                    </div>
                </div>
                <div class="col-md-4">
                    <img src="{{ asset('assets/images/team_01.jpg') }}" class="img-fluid" alt="">
                    <h5 class="text-center" style="margin-top: 15px;">Gérer votre propre demande</h5>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

ProjPiDev/templates/demande_emploi/aff_demande_detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}Votre demande{% endblock %}

{% block body %}
            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Votre demande  {{ demande.TitreDemande }} </h4>
                        <p class="card-description">
                            voir details
                        </p>
                        <div class="table-responsive">
                            <table class="table table-striped">
                                <thead>
                                <tr>
                                    
                                    <th>Titre</th>
                                    <th>Domaine</th>
                                    <th>Statut</th>
                                    <th>Description</th>
                                    <th>CV</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                            
                                    <td>
                                        {{ demande.TitreDemande }}
                                    </td>
                                    <td>
                                        {{ demande.domaineTravail }}
                                    </td>
                                    <td>
                                        {{ demande.statutCand }}
                                    </td>
                                    <td>
                                        {{ demande.description }}
                                    </td>
                                    <td>
                                        <td><a class="btn btn-success" href="{{ asset('uploads/image/' ~ demande.cvCand) }}" download >CV</a></td>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <a class="btn btn-success" href="{{ path('list_demande_emploi') }}">Retour</a>
                </div>
            </div>
{% endblock %}

ProjPiDev/templates/demande_emploi/listdem.html.twig
{% block body %}

    <style>
        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }
        td, th {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }
        tr:nth-child(even) {
            background-color: #dddddd;
        }
    </style>

    <h2>Liste demande d'emploi</h2>
 

    <hr>
    <table>

        <tr>
            <th>Id</th>
            <th>titre</th>
            <th>statut</th>
        </tr>
{% for demande in demandes %}
            <tr>
                <td>{{ demande.id }}</td>
                <td>{{ demande.TitreDemande }}</td>
                <td>{{ demande.statutCand }}</td>
            </tr>
{% endfor %}
    </table>
    <hr>

{% endblock %}

ProjPiDev/templates/demande_emploi/liste_demande_back.html.twig
{% extends 'baseBack.html.twig' %}

{% block title %}Liste demande d'emploi{% endblock %}

{% block body %}

    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Liste des demandes</h4>
                <div class="table-responsive">
                <a class="btn btn-success" href="{{ path('listdem') }}" download>PDF Liste</a>
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Titre</th>
                        <th>Domaine</th>
                        <th>Statut</th>
                        <th>Description</th>
                        <th>Cv</th>
                    </tr>
                    </thead>
                    <tbody>

    {% for demande in demandes %}

                    <tr>
                        <td>{{demande.id}}</td>
                        <td>{{demande.TitreDemande}}</td>
                        <td>{{demande.domaineTravail}}</td>
                        <td>{{demande.statutCand}}</td>
                        <td>{{demande.description}}</td>
                        <td><a class="btn btn-success" href="{{ asset('uploads/image/' ~ demande.cvCand) }}" download >CV</a></td>
                    </tr>

    {% endfor %}

                    </tbody>


                </table>
            </div>
         </div>
        </div>
    </div>








{% endblock %}

ProjPiDev/templates/demande_emploi/liste_demande_emploi.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste demande d'emploi{% endblock %}

{% block body %}
    <div class="page-heading contact-heading header-text" style="background-image: url({{asset('assets/images/heading-4-1920x500.jpg') }});">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="text-content">
                        <h2>Vos demandes</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% for demande in demandes %}
        <div class="best-features">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="section-heading">
                            <h2>Vos demandes</h2>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="left-content">
                            <p> {{ demande.description }} </p>
                            <ul class="featured-list">
                                <li><a>{{demande.TitreDemande}}</a></li>
                                <li><a>{{demande.statutCand}}</a></li>
                                <li><a>{{ demande.domaineTravail }}</a></li>
                            </ul>
                            <a href="{{ path('list_demande_emploi_detail', {'id': demande.id}) }}" class="filled-button">Voir</a>
                            <a href="{{ path('Modif_demande_emploi', {'id': demande.id}) }}" class="filled-button">Modifier</a>
                            <a href="{{ path('Supp_demande_emploi', {'id': demande.id}) }}" class="filled-button">Supprimer</a>
                            <td><a class="btn btn-success" href="{{ asset('uploads/image/' ~ demande.cvCand) }}" download >CV</a></td>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="right-image">
                            <img src="{{ asset('assets/images/about-1-570x350.jpg') }} "alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    {{ knp_pagination_render(
        demandes,
        '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig',
        {
            'queryParam1': 'param1 value',
            'queryParam2': 'param2 value'
        },
        {
            'viewParam1': 'param1 value',
            'viewParam2': 'param2 value'
        },
    ) }}
    {% endblock %}

ProjPiDev/templates/demande_emploi/search.html.twig
{% extends 'base.html.twig' %}

{% block title %}Search{% endblock %}

{% block body %}

    <form method="post" action="{{ path('search') }}">
        <option {{ order is same as('Bac') ? 'selected' : '' }}>Bac</option>
        <option {{ order is same as('Licence') ? 'selected' : '' }}>Licence</option>
        <option {{ order is same as('Doctorat') ? 'selected' : '' }}>Doctorat</option>
        </select>
        <input type="text" name="query" value="{{ query }}" />
    </form>

    <ul>
        {% for result in results %}
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>Image</th>
                        <th>Titre</th>
                        <th>Domaine</th>
                        <th>Statut</th>
                        <th>Description</th>
                        <th>CV</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td class="py-1">
                            <img src="{{ asset('../../images/faces/face1.jpg') }}" alt="image"/>
                        </td>
                        <td>
                            {{ result.TitreDemande }}
                        </td>
                        <td>
                            {{ result.domaineTravail }}
                        </td>
                        <td>
                            {{ result.statutCand }}
                        </td>
                        <td>
                            {{ result.description }}
                        </td>
                        <td>
                            <a class="btn btn-success" href="{{ path('listdem') }}">Voir cv</a>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        {% else %}
            <li>no results found!</li>
        {% endfor %}
    </ul>
{% endblock %}

ProjPiDev/templates/demande_emploi/searchBack.html.twig
{% extends 'baseBack.html.twig' %}

{% block title %}Search{% endblock %}

{% block body %}

    <form method="post" action="{{ path('search') }}">
        <option {{ order is same as('Bac') ? 'selected' : '' }}>Bac</option>
        <option {{ order is same as('Licence') ? 'selected' : '' }}>Licence</option>
        <option {{ order is same as('Doctorat') ? 'selected' : '' }}>Doctorat</option>
        </select>
        <input type="text" name="query" value="{{ query }}" />
    </form>

    <div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
    <div class="card-body">
    <h4 class="card-title">Liste des demandes</h4>
    <div class="table-responsive">
    <table class="table table-hover">
    <thead>
    <tr>
        <th>Id</th>
        <th>Id candidat</th>
        <th>Titre</th>
        <th>Domaine</th>
        <th>Statut</th>
        <th>Description</th>
        <th>CV</th>
        <div class="search-box">
            <form method="post" action="{{ path('tri') }}">
                <label>Trier Reclamation</label>
                <input type="submit" value="Tri">
            </form>
        </div>
    </tr>
    </thead>
    <tbody>
    {% for result in results %}
        <tr>
            <td>{{result.id}}</td>
            <td>{{result.id}}</td>
            <td>{{result.TitreDemande}}</td>
            <td>{{result.domaineTravail}}</td>
            <td>{{result.statutCand}}</td>
            <td>{{result.description}}</td>
            <td>{{result.cvCand}}</td>

        </tr>
    {% endfor %}
    </tbody>
    </table>
    </div>
    </div>
    </div>
    </div>
{% endblock %}